server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
        - id: dentist-service
          uri: lb://dentist-service
          predicates:
            - Path=/dentists/**
        - id: treatment-service
          uri: lb://treatment-service
          predicates:
            - Path=/treatments/**
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoices/**