server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: procedure-service
          uri: lb://procedure-service
          predicates:
            - Path=/procedures/**
