server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    #url: jdbc:mysql://host.docker.internal:49153/service-tramite
    url: jdbc:mysql://localhost:3306/service-tramite
    username: root
    password: mysqladmin
    driverClassName: com.mysql.jdbc.Driver
welcome:
  message: Tramite service
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    mx:
      org:
        ift:
          sihom: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"